#!/usr/bin/env bash
#
# Copyright (c) 2018 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

echo "------ HOOK START - BUILD -------"
printenv

docker build --build-arg PRAVEGA_VERSION=0.3.0-1870.f56b52dd --build-arg PLUGIN_VERSION=0.3.0-SNAPSHOT -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
