#!/usr/bin/env bash
#
# Copyright (c) 2018 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -vuex
echo "------ HOOK START - BUILD -------"
export PRAVEGA_VERSION=`grep pravega-client ../logstash-output-pravega.gemspec  | awk -F"'" '{print $4}'`

# 0.3.0-SNAPSHOT
export PLUGIN_VERSION=`grep s.version ../logstash-output-pravega.gemspec  | awk -F"'" '{print $2}'`

#docker build --build-arg PRAVEGA_VERSION=${PRAVEGA_VERSION} --build-arg PLUGIN_VERSION=0.3.0-SNAPSHOT -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
